version: "3.8"

services:
  adminer-service:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer-service
    depends_on:
      - db
      - nextcloud-db
    networks:
      - memefy_network
    ports:
      - "8081:8080"

  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
        POSTGRES_PASSWORD: ${DB__DB_PASS}
        POSTGRES_USER: ${DB__DB_USER}
        POSTGRES_DB: ${DB__DB_NAME}
    networks:
      - memefy_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn services.web.app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - "8000:8000"

    depends_on:
      - db
      - nextcloud-db
    networks:
      - memefy_network

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - "8082:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: localhost 10.12.189.153
    depends_on:
      - nextcloud-db
    networks:
      memefy_network:
        aliases:
          - nextcloud

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db 
    restart: unless-stopped 
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      - memefy_network
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}

volumes:
  postgres_data:
  nextcloud_data:
  nextcloud_db_data:

networks:
  memefy_network:
